### ISSUE TITLE
Ansteuerung Motor

### ISSUE THREAD

**Issue by WengaBergbauer** [LukasPrommeg/T003_StretPro_II#17]
Der Raspberry soll die Eingabe der Website entgegen nehmen und die Motorgeschwindigkeit (0-100) entsprechend steuern

**Comment by LukasPrommeg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StretPro2-63be7eacedf0d30015e4bbe3/issues/LukasPrommeg/T003_StretPro_II/17?planning-poker) with Zenhub @johannes420 @LeonRothauer @LukasPrommeg @WengaBergbauer
