### ISSUE TITLE
Verbindung über bestehendes WLAN

### ISSUE THREAD

**Issue by LukasPrommeg** [LukasPrommeg/T003_StretPro_II#7]
Das Teller soll in Lage sein sich mit einem angegeben WLAN zu verbinden

**Comment by LeonRothauer** [comment]
:D

**Comment by LukasPrommeg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StretPro2-63be7eacedf0d30015e4bbe3/issues/LukasPrommeg/T003_StretPro_II/7?planning-poker) with Zenhub @johannes420 @LeonRothauer @LukasPrommeg @WengaBergbauer
